model_list:
  - model_name: claude-sonnet-5-5
    litellm_params:
      model: github_copilot/claude-sonnet-5.5

  - model_name: claude-opus-5-5
    litellm_params:
      model: github_copilot/claude-opus-5.5

  - model_name: claude-haiku-4-5
    litellm_params:
      model: github_copilot/claude-haiku-4.5

litellm_settings:
  drop_params: true

general_settings:
  master_key: "sk-litellm-local"
